### ISSUE TITLE
Cannot run installation test too

### ISSUE THREAD

**Issue by ddddg929** [imagej/pyimagej#104]
Hi, sorry to disturb you! Can someone help me!
After installed pyimagej in conda environment with instruction, and run `python -c 'import imagej; ij = imagej.init('2.1.0'); print(ij.getVersion()); ij.dispose()'`,
it returned 
` File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal`
I do not know why.
![image](https://user-images.githubusercontent.com/61380549/111316537-4f666f00-869e-11eb-89bf-c28db817fb7d.png)
And I tired to run code in spyder in pyimagej environment with
`import imagej`
 `ij = imagej.init('sc.fiji:fiji')`
it return:

Error in `D:\Anaconda3\envs\pyimagej\Library\bin\mvn.CMD -B -f C:\Users\admin2\.jgo\net.imglib2\imglib2-imglyb\1.0.0+net.imagej-imagej-legacy-RELEASE+sc.fiji-fiji-RELEASE\pom.xml dependency:resolve': 1 An exception has occurred, use %tb to see the full traceback.
 Traceback (most recent call last):    File "D:\Anaconda3\envs\pyimagej\lib\site-packages\jgo\jgo.py", line 201, in run_and_combine_outputs     return subprocess.check_output((command,) + args, stderr=subprocess.STDOUT)    File "D:\Anaconda3\envs\pyimagej\lib\subprocess.py", line 415, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,    File "D:\Anaconda3\envs\pyimagej\lib\subprocess.py", line 516, in run     raise CalledProcessError(retcode, process.args,  CalledProcessError: Command '('D:\\Anaconda3\\envs\\pyimagej\\Library\\bin\\mvn.CMD', '-B', '-f', 'C:\\Users\\admin2\\.jgo\\net.imglib2\\imglib2-imglyb\\1.0.0+net.imagej-imagej-legacy-RELEASE+sc.fiji-fiji-RELEASE\\pom.xml', 'dependency:resolve')' returned non-zero exit status 1.
  During handling of the above exception, another exception occurred:  SystemExit: 1

![image](https://user-images.githubusercontent.com/61380549/111317791-6fe2f900-869f-11eb-9d0b-e56cac03ef93.png)

**Comment by ddddg929** [comment]
"""
(pyimagej) C:\Users\admin2>conda list
# packages in environment at D:\Anaconda3\envs\pyimagej:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
astroid                   2.5.1            py38haa244fe_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
autopep8                  1.5.5              pyh44b312d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py38h294d835_1    conda-forge
black                     20.8b1                     py_1    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.4.6            py38hd7da0ea_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.16             py38haa244fe_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    3.8.4                      py_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
helpdev                   0.7.1              pyhd8ed1ab_0    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
imglyb                    1.0.0              pyh050c7b8_0    conda-forge
importlib-metadata        3.7.3            py38haa244fe_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.5.0            py38hc5df569_1    conda-forge
ipython                   7.21.0           py38hc5df569_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.7.0              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py38haa244fe_1    conda-forge
jgo                       1.0.0              pyhd8ed1ab_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
jpype1                    1.2.1            py38hbd9d945_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   22.3.0           py38haa244fe_0    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
lazy-object-proxy         1.5.2            py38h294d835_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
markupsafe                1.1.1            py38h294d835_3    conda-forge
matplotlib-base           3.3.4            py38h34ddff4_0    conda-forge
maven                     3.6.0                         0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38h294d835_1003    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mypy_extensions           0.4.3            py38haa244fe_3    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38haa244fe_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
numpy                     1.20.1           py38h0cc643e_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjdk                   8.0.265                       0    conda-forge
openssl                   1.1.1j               h8ffe710_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.3            py38h4c96930_0    conda-forge
pandoc                    2.12                 h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py38h9273828_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py38haa244fe_4    conda-forge
prompt-toolkit            3.0.17             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                5.1.1                      py_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pyimagej                  1.0.0            py38haa244fe_0    conda-forge
pylint                    2.7.2            py38haa244fe_0    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.2              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py38h31c79cd_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38haa244fe_7    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_7    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_7    conda-forge
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_7    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.8           h7840368_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1003    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
pyzmq                     22.0.3           py38h09162b1_1    conda-forge
qdarkstyle                2.8.1              pyhd8ed1ab_2    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.2              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
regex                     2020.11.13       py38h294d835_1    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py38h8b54edf_1    conda-forge
scyjava                   1.1.0              pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    4.2.3            py38haa244fe_0    conda-forge
spyder-kernels            1.10.2           py38haa244fe_0    conda-forge
sqlite                    3.34.0               h8ffe710_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
textdistance              4.2.1              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.2            py38h294d835_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
ujson                     4.0.2            py38h885f38d_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
watchdog                  1.0.2            py38haa244fe_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
wrapt                     1.12.1           py38h294d835_3    conda-forge
xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge
"""

**Comment by ddddg929** [comment]
update question:
```

(pyimagej) C:\Users\duzhenhong>python -c "import imagej; ij = imagej.init('2.1.0'); print(ij.getVersion()); ij.dispose()"
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 226, in org.scijava.util.Types.load
  File "ClassLoader.java", line 352, in java.lang.ClassLoader.loadClass
  File "Launcher.java", line 352, in sun.misc.Launcher$AppClassLoader.loadClass
  File "ClassLoader.java", line 419, in java.lang.ClassLoader.loadClass
  File "URLClassLoader.java", line 382, in java.net.URLClassLoader.findClass
java.lang.ClassNotFoundException: java.lang.ClassNotFoundException: net.imagej.legacy.LegacyService

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "AbstractGateway.java", line 135, in org.scijava.AbstractGateway.get
  File "Context.java", line 324, in org.scijava.Context.service
  File "Types.java", line 155, in org.scijava.util.Types.load
  File "Types.java", line 234, in org.scijava.util.Types.load
  File "Types.java", line 975, in org.scijava.util.Types.iae
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\software\anaconda\envs\pyimagej\lib\site-packages\imagej\__init__.py", line 194, in init
    legacyServiceObj = ij.get('net.imagej.legacy.LegacyService')
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot load class: net.imagej.legacy.LegacyService

(pyimagej) C:\Users\duzhenhong>          
```

**Comment by ddddg929** [comment]
look like same to #103

**Comment by ddddg929** [comment]
Is this error negligible? 
```
(pyimagej) C:\Users\admin2>python -c "import imagej; ij=imagej.init('sc.fiji:fiji');print(ij.getVersion()); ij.dispose()"
Error in `D:\Anaconda3\envs\pyimagej\Library\bin\mvn.CMD -B -f C:\Users\admin2\.jgo\net.imglib2\imglib2-imglyb\1.0.0+net.imagej-imagej-legacy-RELEASE+sc.fiji-fiji-RELEASE\pom.xml dependency:resolve': 1
```
