### ISSUE TITLE
Unable to get the current image from “WindowManager.getCurrentImage()”

### ISSUE THREAD

**Issue by ddddg929** [imagej/pyimagej#109]
Dear all,
  I have a 16 bit image, and I want to use ImageJ to enhance its contrast, and then binarize it. My code is as follows：

```
import imagej
from scyjava import jimport
from skimage import io
from tifffile import imwrite
import numpy as np

ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10',headless=False)

image = io.imread("E:\\Data for python\\code\\pingjie\\21_04_1_brain_slice\\2.tif")

ij.ui().show('enhanced image', ij.py.to_java(image))
ij.py.run_macro("""run("Enhance Contrast...", "saturated=0.3 normalize equalize");""")
ij.py.run_macro("""run("8-bit");""")

WindowManager = jimport('ij.WindowManager')

bb = WindowManager.getCurrentImage()
print(bb)
img_from_ij = ij.py.from_java(bb)



# plot the image (xarr)
ij.py.show(img_from_ij, cmap='gray')

imwrite('E:\\Data for python\\code\\pingjie\\21_04_1_brain_slice\\2_1.tif',img_from_ij)
```

```
Display in Python console


PyDev console: starting.
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)] on win32
>>> runfile('E:/Data for python/code/pyimagej/utitled1.py', wdir='E:/Data for python/code/pyimagej')
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
20:06:39.542 [SciJava-514eedd8-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.URLReader
java.lang.ClassNotFoundException: loci.formats.in.URLReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at loci.formats.ClassList.parseLine(ClassList.java:196)
	at loci.formats.ClassList.parseFile(ClassList.java:258)
	at loci.formats.ClassList.<init>(ClassList.java:138)
	at loci.formats.ClassList.<init>(ClassList.java:122)
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80)
	at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:538)
	at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:139)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:234)
	at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:223)
	at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:214)
	at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:459)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:06:39.553 [SciJava-514eedd8-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.SlideBook6Reader
java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at loci.formats.ClassList.parseLine(ClassList.java:196)
	at loci.formats.ClassList.parseFile(ClassList.java:258)
	at loci.formats.ClassList.<init>(ClassList.java:138)
	at loci.formats.ClassList.<init>(ClassList.java:122)
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80)
	at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:538)
	at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:139)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:234)
	at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:223)
	at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:214)
	at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:459)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
20:06:39.554 [SciJava-514eedd8-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ScreenReader
java.lang.ClassNotFoundException: loci.formats.in.ScreenReader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at loci.formats.ClassList.parseLine(ClassList.java:196)
	at loci.formats.ClassList.parseFile(ClassList.java:258)
	at loci.formats.ClassList.<init>(ClassList.java:138)
	at loci.formats.ClassList.<init>(ClassList.java:122)
	at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:80)
	at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:538)
	at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:139)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:304)
	at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:234)
	at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:223)
	at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:214)
	at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:459)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
img["enhanced image" (-2), 8-bit, 10376x7512x1x1x1]
```

But I cannot get the enhanced 8 bit from bb, this is the processed image after  macro(I want to get )
![image](https://user-images.githubusercontent.com/61380549/113414784-60c6af80-93f0-11eb-9e2d-79132f8b90e5.png)
and I print bb , it shows:
`img["enhanced image" (-2), 8-bit, 10376x7512x1x1x1]`
however , when I write the image after using  `ij.py.from_java(bb)` , I did not get the enhanced 8 bit image , The image I get is the data I read ,like this 
![image](https://user-images.githubusercontent.com/61380549/113415064-fd894d00-93f0-11eb-8bb9-b782a4c5f799.png)
I don't know why, can someone kind help me!

**Comment by ddddg929** [comment]
This is the raw image I use.Raw tiff image is too big to upload it .
![1](https://user-images.githubusercontent.com/61380549/113415490-e434d080-93f1-11eb-8586-249c37492992.PNG)

**Comment by ddddg929** [comment]
And I dont not how to make binary image. I use this macro,
```

macro = """
setOption("BlackBackground", true);
run("Convert to Mask");
"""
ij.py.run_macro(macro)

```
 I got an all black image

**Comment by imagejan** [comment]
@ddddg929 wrote:
> however , when I write the image after using ij.py.from_java(bb) , I did not get the enhanced 8 bit image , The image I get is the data I read

I didn't test yet, but this *might* be an issue of IJ1<->IJ2 synchronization (the macro works on the `ImagePlus`, but the pixel data are from the not-yet-synchronized `Dataset`??), see this related issue:

https://github.com/imagej/imagej-legacy/issues/231

---

> I got an all black image

Did you try to set a threshold first, before converting to mask?

**Comment by ddddg929** [comment]
Thanks for your kind reply! @imagejan
