### ISSUE TITLE
jgo.jgo.ExecutableNotFound: mvn not found on path

### ISSUE THREAD

**Issue by fanweiya** [imagej/pyimagej#118]
I get jgo.jgo.ExecutableNotFound: mvn not found on path error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\fanweiya\.virtualenvs\pinjie-MK4kbU1v\lib\site-packages\imagej\__init__.py", line 162, in init
    sj.start_jvm()
  File "C:\Users\fanweiya\.virtualenvs\pinjie-MK4kbU1v\lib\site-packages\scyjava\__init__.py", line 51, in start_jvm
    verbose=scyjava.config.get_verbose()
  File "C:\Users\fanweiya\.virtualenvs\pinjie-MK4kbU1v\lib\site-packages\jgo\jgo.py", line 471, in resolve_dependencies
    mvn     = executable_path_or_raise('mvn')
  File "C:\Users\fanweiya\.virtualenvs\pinjie-MK4kbU1v\lib\site-packages\jgo\jgo.py", line 138, in executable_path_or_raise
    raise ExecutableNotFound(tool, os.getenv('PATH'))
jgo.jgo.ExecutableNotFound: mvn not found on path C:\Users\fanweiya\.virtualenvs\pinjie-MK4kbU1v\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Tailscale IPN;D:\Program Files\anaconda;D:\Program Files\anaconda\Library\mingw-w64\bin;D:\Program Files\anaconda\Library\usr\bin;D:\Program Files\anaconda\Library\bin;D:\Program Files\anaconda\Scripts;C:\Users\fanweiya\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\fanweiya\AppData\Local\Programs\Python\Python37\;C:\Users\fanweiya\AppData\Local\Microsoft\WindowsApps;c:\program files\esafenet\cobra docguard client;D:\Program Files\Git\cmd;C:\Users\fanweiya\.virtualenvs\pinjie-MK4kbU1v\lib\site-packages\numpy\.libs
```

**Comment by imagejan** [comment]
You need Maven (`mvn`) installed in your environment.

When installing via conda as described on the README, mvn should be part of your environment already.

**Comment by fanweiya** [comment]
thanks
