### ISSUE TITLE
win10, conda, problem to run example

### ISSUE THREAD

**Issue by WT215** [imagej/pyimagej#163]
Hello, I want to deploy pyimagej in my win10 conda environment (created via `conda create -n pyimagej -c conda-forge pyimagej openjdk=8 python=3.7`), but the following test code failed:
```
image_url = 'D:/debug.png'

import imagej
import scyjava
import jgo
scyjava.config.add_option('-Xmx6g')
ij = imagej.init('D:/Fiji.app', headless=False) 
jimage = ij.io().open(image_url)
```
Error message is:

```
jimage = ij.io().open(image_url)
Traceback (most recent call last):

  File "DefaultIOService.java", line 68, in org.scijava.io.DefaultIOService.open

  File "DefaultIOService.java", line 87, in org.scijava.io.DefaultIOService.open

  File "IOService.java", line 62, in org.scijava.io.IOService.getOpener

  File "DatasetIOPlugin.java", line 75, in io.scif.io.DatasetIOPlugin.supportsOpen

  File "DefaultDatasetIOService.java", line 87, in io.scif.services.DefaultDatasetIOService.canOpen

  File "DefaultFormatService.java", line 323, in io.scif.services.DefaultFormatService.getFormat

  File "DefaultFormatService.java", line 347, in io.scif.services.DefaultFormatService.getFormatList

  File "AbstractChecker.java", line 84, in io.scif.AbstractChecker.isFormat

Exception: Java Exception


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-77-a6ee71aaa596>", line 1, in <module>
    jimage = ij.io().open(image_url)

java.lang.NullPointerException: java.lang.NullPointerException
```
It works ok under Linux environment, but win10 is more convenient for me so far.

Thanks a lot!

**Comment by WT215** [comment]
Figured out, should be `ij = imagej.init('D:\\Fiji.app')` and `'D:\\debug.png'` 

I also deleted FilamentDetector-1.0.0 (not sure what impact would that be).

Now imagej seems to work in python.
