### ISSUE TITLE
ImportError: Your IJ endpoint does not support IJ1, and thus cannot use IJ1 macros.

### ISSUE THREAD

**Issue by LisaVdB** [imagej/pyimagej#168]
Hi, 

I have a simple python script that runs a macro using the pyimagej module. It splits an image into it's different channels and performs a z-projection on one of the channels. This z-projection is saved as png. The script works fine ones and outputs the png images. However, when I run it a second time, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Google_Drive\Post-doc\Project_3D-bioprinter\Modeling Code\ImageAnalysisPipeline\Confocal-z-stack-cell-detection\src\BF_BlobDetector.py", line 44, in png_converter
    ij.py.run_macro(macro)
  File "C:\Users\lisav\AppData\Local\R-MINI~1\envs\r-reticulate\lib\site-packages\imagej\__init__.py", line 358, in run_macro
    raise ImportError("Your IJ endpoint does not support IJ1, and thus cannot use IJ1 macros.")
ImportError: Your IJ endpoint does not support IJ1, and thus cannot use IJ1 macros.`

This is the version of the imagej initialization:
>>> ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
>>> print(ij.getVersion())
2.0.0-rc-71/Inactive

Everything is functional again only after restarting python. Any ideas on why the script can run only ones? For my specific application, I need the script to run multiple times. 

This is the output when initializing the first time (when everything still works):
>>> ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
14:05:11.071 [SciJava-4745e9c-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.SlideBook6Reader
java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at loci.formats.ClassList.parseLine(ClassList.java:196)
        at loci.formats.ClassList.parseFile(ClassList.java:258)
        at loci.formats.ClassList.<init>(ClassList.java:138)
        at loci.formats.ClassList.<init>(ClassList.java:122)
        at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:79)
        at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:489)
        at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:138)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
        at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
        at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
        at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:458)
        at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
14:05:11.077 [SciJava-4745e9c-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ScreenReader
java.lang.ClassNotFoundException: loci.formats.in.ScreenReader
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at loci.formats.ClassList.parseLine(ClassList.java:196)
        at loci.formats.ClassList.parseFile(ClassList.java:258)
        at loci.formats.ClassList.<init>(ClassList.java:138)
        at loci.formats.ClassList.<init>(ClassList.java:122)
        at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:79)
        at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:489)
        at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:138)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
        at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
        at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
        at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:458)
        at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.imagej.patcher.LegacyInjector (file:/C:/Users/lisav/.jgo/sc.fiji/fiji/cf5b9cfa780ed57120a6bfbf9ba822458a22ccc79d9a902d6a854c3f13849d4a/ij1-patcher-0.12.9.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of net.imagej.patcher.LegacyInjector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
>>> print(ij.getVersion())
2.0.0-rc-71/1.52i
```
Thank you very much !

**Comment by ctrueden** [comment]
@LisaVdB Each time you call `ij = imagej.init(...)`, it creates a new application context. If you are using "pure ImageJ2" this is fine... but due to limitations in how ImageJ2's backward compatibility layer with ImageJ works, only one of these application contexts can be "original-ImageJ-enabled" at a time. So because you are attempting to use `ij.py.run_macro` (an function of the original ImageJ, not pure ImageJ2) with one of these latter non-original-ImageJ-enabled contexts, you are getting that error.

To avoid it, you can either:

1. call `ij.dispose()` before doing another `ij = imagej.init(...)`; or
2. (easier IMHO) create only a single `ij` object ever for the lifetime of your Python runtime, and just reuse it for all the operations you want to perform.

If you decide to go with option (2), you can even retrieve your `ij` from the `imagej` module since it gets stashed as a global variable:

```python
>>> import imagej
>>> ij = imagej.init()
>>> ij.getVersion()
'2.3.0/1.53f'
>>> ij = None
>>> ij = imagej.ij
>>> ij.getVersion()
'2.3.0/1.53f'
```

As for the `ClassNotFoundException` stack traces: those are emitted by Bio-Formats and are harmless. They should disappear once I figure out how to solve #41. :smile:

**Comment by LisaVdB** [comment]
Awesome ! I followed your advice and created a single `ij` object for my entire Python runtime and that works perfectly.
