### ISSUE TITLE
Plugin ComDet

### ISSUE THREAD

**Issue by LisaVdB** [imagej/pyimagej#173]
Hi, 

I want to run a macro that uses the ComDet plugin (https://github.com/ekatrukha/ComDet). I tried adding the plugin as follow:

`import scyjava` 
`plugins_dir = '/plugins'`
`scyjava.config.add_option(f'-Dplugins.dir={plugins_dir}')`
`ij = imagej.init(['sc.fiji:fiji:2.0.0-pre-10', 'net.imagej:imagej-legacy'])`

And I also tried:

`ij = imagej.init(['sc.fiji:fiji:2.0.0-pre-10',  'net.ekatrukha:ComDet:0.5.5'])`

I get the following error: 
>>> ij.py.run_macro(macro_gf)
[ERROR]: Cannot locate JRE jar in C:\Users\lisav\AppData\Local\r-miniconda\envs\r-reticulate\Library
[java.lang.Enum.toString] [ERROR]: Cannot locate JRE jar in C:\Users\lisav\AppData\Local\r-miniconda\envs\r-reticulate\Library[java.lang.Enum.toString]
[ERROR] Cannot create plugin: class='org.scijava.ui.swing.script.languagesupport.JavaLanguageSupportPlugin', priority=0.0, enabled=true, pluginType=LanguageSupportPlugin
java.lang.IllegalArgumentException: info cannot be null
        at org.fife.rsta.ac.java.JarManager.addClassFileSource(JarManager.java:157)
        at org.fife.rsta.ac.java.JarManager.addCurrentJreClassFileSource(JarManager.java:193)
        at org.scijava.ui.swing.script.languagesupport.JavaLanguageSupportPlugin.<init>(JavaLanguageSupportPlugin.java:56)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
        at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
        at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
        at org.scijava.plugin.AbstractSingletonService.initInstances(AbstractSingletonService.java:138)
        at org.scijava.plugin.AbstractSingletonService.getInstances(AbstractSingletonService.java:77)
        at org.scijava.plugin.SingletonService.lambda$initialize$0(SingletonService.java:97)
        at org.scijava.object.ObjectIndex.resolvePending(ObjectIndex.java:388)
        at org.scijava.object.ObjectIndex.get(ObjectIndex.java:133)
        at org.scijava.object.DefaultObjectService.getObjects(DefaultObjectService.java:87)
        at org.scijava.module.DefaultModuleService.getRegisteredModuleInstance(DefaultModuleService.java:381)
        at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:166)
        at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:209)
        at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:200)
        at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:185)
        at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:183)
        at org.scijava.script.ScriptService.run(ScriptService.java:244)
        at org.scijava.script.ScriptService.run(ScriptService.java:194)
[java.lang.Enum.toString] [ERROR] Cannot create plugin: class='org.scijava.ui.swing.script.languagesupport.JavaLanguageSupportPlugin', priority=0.0, enabled=true, pluginType=LanguageSupportPlugin
java.lang.IllegalArgumentException: info cannot be null
        at org.fife.rsta.ac.java.JarManager.addClassFileSource(JarManager.java:157)
        at org.fife.rsta.ac.java.JarManager.addCurrentJreClassFileSource(JarManager.java:193)
        at org.scijava.ui.swing.script.languagesupport.JavaLanguageSupportPlugin.<init>(JavaLanguageSupportPlugin.java:56)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
        at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
        at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
        at org.scijava.plugin.AbstractSingletonService.initInstances(AbstractSingletonService.java:138)
        at org.scijava.plugin.AbstractSingletonService.getInstances(AbstractSingletonService.java:77)
        at org.scijava.plugin.SingletonService.lambda$initialize$0(SingletonService.java:97)
        at org.scijava.object.ObjectIndex.resolvePending(ObjectIndex.java:388)
        at org.scijava.object.ObjectIndex.get(ObjectIndex.java:133)
        at org.scijava.object.DefaultObjectService.getObjects(DefaultObjectService.java:87)
        at org.scijava.module.DefaultModuleService.getRegisteredModuleInstance(DefaultModuleService.java:381)
        at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:166)
        at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:209)
        at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:200)
        at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:185)
        at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:183)
        at org.scijava.script.ScriptService.run(ScriptService.java:244)
        at org.scijava.script.ScriptService.run(ScriptService.java:194)
Plugin or class not found: "fiji.plugin.ComDet.Detect_Particles"
(java.lang.ClassNotFoundException: fiji.plugin.ComDet.Detect_Particles)[java.lang.Enum.toString] Plugin or class not found: "fiji.plugin.ComDet.Detect_Particles"
(java.lang.ClassNotFoundException: fiji.plugin.ComDet.Detect_Particles)
[java.lang.Enum.toString]
<java object 'org.scijava.script.ScriptModule'>

Can you help me figuring out how I can fix this ?

Thank you so much !

**Comment by LisaVdB** [comment]
Using a local installation works ! I can't extract the results yet though, but I will do some troubleshooting. 
I was guessing with the 'net.ekatrukha:ComDet:0.5.5' string. I saw an example on one of your docs and I tried to replicate it. 
Thanks a lot!

**Comment by ctrueden** [comment]
@ekatrukha Just a heads up: your plugin is being used with PyImageJ! :+1: If you want to make it easier to do that, especially on the cloud, you could consider building and publishing it to maven.scijava.org. If you're interested, feel free to file an issue about it on the [pom-scijava issue tracker](https://github.com/scijava/pom-scijava/issues) and I'd be happy to help.
