### ISSUE TITLE
Set JAVA_HOME to CONDA_PREFIX if not already set

### ISSUE THREAD

**Issue by somsubhro88** [imagej/pyimagej#176]
Hello all,

I am not sure if there is a particular location to find a concrete solution to an initialisation problem, but I can't seem to find the right steps, even after looking in a lot of posts.

This is where I downloaded/installed ImageJ from - https://imagej.net/software/fiji/downloads (Windows 64-bit)

This is what I followed: https://github.com/imagej/pyimagej/blob/master/doc/Install.md

I already had Anaconda installed, so I opened Anaconda Powershell Prompt (anaconda3), and then typed in the following - 
```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
This was followed by
```
conda create -n pyimagej pyimagej openjdk=8
```

Ultimately, I typed - 
```
conda activate pyimagej
```

Following this, I opened spyder in the same environment, and then ran the following code:

```
import imagej  

fiji_path = 'C:/Users/schaudhu/Documents/Fiji.app'  # should be a folder

# initialise ImageJ
print('initialising ImageJ ...')
ij = imagej.init(fiji_path, headless=False)
ij.ui().showUI()  # gives the imageJ ui for manual usage, if headless=False
print('ImageJ initialised')
```

I get this error:
```

  File "C:\Users\schaudhu\Documents\FLUXYS\PYTHON_WD\hydrogen_emb\image_processing\untitled0.py", line 13, in <module>
    ij = imagej.init(fiji_path, headless=False)

  File "C:\ProgramData\Anaconda3\lib\site-packages\imagej\__init__.py", line 165, in init
    sj.start_jvm()

  File "C:\ProgramData\Anaconda3\lib\site-packages\scyjava\__init__.py", line 59, in start_jvm
    jpype.startJVM(*options, interrupt=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jpype\_core.py", line 192, in startJVM
    jvmpath = getDefaultJVMPath()

  File "C:\ProgramData\Anaconda3\lib\site-packages\jpype\_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()

  File "C:\ProgramData\Anaconda3\lib\site-packages\jpype\_jvmfinder.py", line 212, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "

JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.
```

I don't seem to find one concrete solution for this. I tried the following lines of code in Powershell BOTH before and after loading the pyimagej environment:

```
set "JAVA_HOME=C:\Users\schaudhu\.conda\envs\pyimagej\Library"
```
Got the same error.

Could someone please help? I am sorry if I am repeating other issues, but I can't seem to identify the correct list of commands to fix this issue :(

**Comment by ctrueden** [comment]
No worries @somsubhro88, I'll try to help, although I don't use Windows regularly.

It is unfortunate that `JAVA_HOME` is not already set for you. If you open a fresh PowerShell prompt, activate the pyimagej environment, and then type `echo %JAVA_HOME%`, do you see a valid path? Perhaps `C:\Users\schaudhu\.conda\envs\pyimagej`? If so, then your `JAVA_HOME` is already set, and something else might be going on.

Another question is whether the value of `JAVA_HOME` will propagate successfully into Spyder when you launch it from PowerShell. Windows is weird in that it has two different kinds of applications: console and so-called "Win32", i.e. graphical applications that break their linkage to the console, even when started from a console.

So, in Spyder, before starting PyImageJ, you could try:
```python
import os
print(os.environ['JAVA_HOME'])
```
and see if there is anything there. And if not, you could try:
```python
os.environ['JAVA_HOME'] = 'C:\\Users\\schaudhu\\.conda\\envs\\pyimagej'
```
Note the double backslashes. And note also that I didn't include the `Library` directory... at least on macOS, the `JAVA_HOME` needs to point directly to the conda environment, not a subdirectory thereof. Have you verified that you have a `jvm.dll` somewhere within your `pyimagej` conda environment directory? Installing `openjdk=8` should have dropped one in there for you, but it's good to be sure.

Finally, if none of the above is fruitful, you could try installing [Zulu OpenJDK 8](https://www.azul.com/downloads/?version=java-8-lts&os=windows&package=jdk-fx) system-wide for your architecture (32-bit or 64-bit), and then setting `JAVA_HOME` globally using the Windows Control Panel, and then logging out and back in, and see if that makes any difference.

**Comment by somsubhro88** [comment]
Hello @ctrueden ,

Thank you for responding. 

I tried in a new instance of Anaconda3 powershell `echo %JAVA_HOME%`, but it returned nothing. I guess JAVA_HOME is not set correctly in the first place. I tried defining a JAVA_HOME path using this [link](https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html), but it still didn't really work.

However, your second solution worked :) :) I defined the `os.environ` path correctly. This works for me now (ImageJ pops open):
```

import imagej
import os
os.environ["JAVA_HOME"] = 'C:\\Users\\schaudhu\\Anaconda3\\envs\\pyimagej'

fiji_path = 'C:/Users/schaudhu/OneDrive - UGent/Documents/SOM_Programs/fiji-win64/Fiji.app'

# initialise ImageJ
print('initialising ImageJ ...')
ij = imagej.init(fiji_path, headless=False)
ij.ui().showUI()  # gives the imageJ ui for manual usage, if headless=False
print('ImageJ initialised')
```
Thank you, @ctrueden .

**Comment by somsubhro88** [comment]
Hello @ctrueden ,

Interestingly, the solution above worked on my laptop with Windows 10 enterprise (with an old but updated installation of ImageJ). However, on our workstation (Windows Server) with a newly downloaded version of ImageJ (link above), I now get the following error:

`java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Invalid service: sc.fiji.filamentdetector.gui.GUIStatusService`

To solve this, I copied the older installation of ImageJ into the workstation, and it worked. My conclusion is that the newer installation of ImageJ caused the above problem.

**Comment by somsubhro88** [comment]
Hello @ctrueden 

I ran both Help-Update ImageJ and Help-Update. ImageJ now opens, but I get the following warning:

```
java.lang.IllegalArgumentException: Method void createMacro() in ij.plugin.frame.Recorder does not return on null
	at net.imagej.patcher.CodeHacker.dontReturnOnNull(CodeHacker.java:497)
	at net.imagej.patcher.LegacyExtensions.addEditorExtensionPoints(LegacyExtensions.java:322)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:289)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:285)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
java.lang.IllegalArgumentException: Cannot handle replace call to runPlugIn in ij.plugin.frame.Recorder's void createMacro()
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:723)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:648)
	at net.imagej.patcher.LegacyExtensions.addEditorExtensionPoints(LegacyExtensions.java:323)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:289)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:285)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
Caused by: javassist.CannotCompileException: No code replaced!
	at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1290)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:720)
25 more
java.lang.IllegalArgumentException: Cannot handle replace call to openImage in ij.plugin.FolderOpener's public void run(java.lang.String arg)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:723)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:648)
	at net.imagej.patcher.LegacyExtensions.installOpenInterceptor(LegacyExtensions.java:766)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:296)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:306)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:107)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:100)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:494)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:395)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:374)
	at net.imagej.legacy.LegacyService.<clinit>(LegacyService.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scijava.service.ServiceHelper.createServiceRecursively(ServiceHelper.java:300)
	at org.scijava.service.ServiceHelper.createExactService(ServiceHelper.java:267)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:229)
	at org.scijava.service.ServiceHelper.loadService(ServiceHelper.java:192)
	at org.scijava.service.ServiceHelper.loadServices(ServiceHelper.java:164)
	at org.scijava.Context.<init>(Context.java:285)
	at org.scijava.Context.<init>(Context.java:234)
	at org.scijava.Context.<init>(Context.java:174)
	at org.scijava.Context.<init>(Context.java:160)
	at net.imagej.ImageJ.<init>(ImageJ.java:77)
Caused by: javassist.CannotCompileException: No code replaced!
	at net.imagej.patcher.CodeHacker$EagerExprEditor.instrument(CodeHacker.java:1290)
	at net.imagej.patcher.CodeHacker.replaceCallInMethod(CodeHacker.java:720)
25 more
```

**Comment by ctrueden** [comment]
That error happens because you ran _Help &rarr; Update ImageJ..._ and chose a too-new version of the original ImageJ. ImageJ2 does not support versions of the original ImageJ newer than 1.53f. Do you require a newer version than that? If not, please use _Help &rarr; Update..._ to restore the `jars/ij.jar` to the officially supported version.

I'm sorry the naming around these things is so complicated, but we are where we are.

**Comment by somsubhro88** [comment]
@ctrueden 

You are right, I "downgraded" to v1.52v, and now it works!

**Comment by ctrueden** [comment]
Glad your problems are resolved, @somsubhro88. I'm leaving this issue open due to the fact that you had to set JAVA_HOME manually. There is another environment variable CONDA_PREFIX pointing to the same location, so we could add logic to set JAVA_HOME to CONDA_PREFIX in case JAVA_HOME is not already set correctly. I changed the issue title accordingly.

**Comment by ctrueden** [comment]
I believe this issue is resolved now with a2e65162c12d91197a05ae038e5c48d200bc6002: if `JAVA_HOME` is unset, we try to find a suitable value based on the `sys.path`. This is more general than only looking at `CONDA_PREFIX`, since it works even when the conda environment is not activated. It works well cross-platform in my tests so far.

**Comment by somsubhro88** [comment]
Hello @ctrueden ,

Hello again!

I tried to follow the same steps and install pyimagej today on the same workstation (Windows 10 server) but for another user, I faced an issue. I followed the same steps above and the recommended fix you suggested, but I now get the following error below. Any suggestions?

> Failed to bootstrap the artifact.
> 
> 
> 
> Possible solutions:
> * Double check the endpoint for correctness (https://search.maven.org/).
> * Add needed repositories to ~/.jgorc [repositories] block (see README).
> * Try with an explicit version number (release metadata might be wrong).
> 
> 
> 
> Full Maven error output:
> 
> 
> 
> Traceback (most recent call last):
> 
> 
> 
> File "C:\Users\ldpue.UGENT\.conda\envs\pyimagej\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
> exec(code, globals, locals)
> 
> 
> 
> File "g:\fluxys\for_laura\fluxys\python_wd\hydrogen_emb\image_processing\fluxys_imagej_postprocess.py", line 74, in <module>
> ij = imagej.init(fiji_path, headless=False)
> 
> 
> 
> File "C:\Users\ldpue.UGENT\.conda\envs\pyimagej\lib\site-packages\imagej\__init__.py", line 1498, in init
> raise RuntimeError("Failed to create a JVM with the requested environment.")
> 
> 
> 
> RuntimeError: Failed to create a JVM with the requested environment.

**Comment by CanYing0913** [comment]
Following the whole process of fixes of this post, and I am facing the same issue as @somsubhro88 has:
```
Failed to bootstrap the artifact.

Possible solutions:
* Double check the endpoint for correctness (https://search.maven.org/).
* Add needed repositories to ~/.jgorc [repositories] block (see README).
* Try with an explicit version number (release metadata might be wrong).

Full Maven error output:

Traceback (most recent call last):
  File "D:\CanYing\Code\Columbia\pyimgj.py", line 26, in <module>
    ij = imagej.init('sc.fiji:fiji')
  File "C:\Users\wyari\.conda\envs\caiman\lib\site-packages\imagej\__init__.py", line 1498, in init
    raise RuntimeError("Failed to create a JVM with the requested environment.")
RuntimeError: Failed to create a JVM with the requested environment.
```

**Comment by ctrueden** [comment]
Thanks @CanYing0913. Let's follow up in #206, where @somsubhro88 has posted the more detailed debugging output. I'm taking another look now.
