### ISSUE TITLE
Failed to bootstrap the artifact / Full Maven error output

### ISSUE THREAD

**Issue by lsdanttas** [imagej/pyimagej#220]
Hello!

I tried install pyimagej on a Windows 10 server PC but I'm getting a huge error message when a try to run this (obs: I'm trying to run it on VScode):

```
import imagej

ij = imagej.init('C:\\Users\\--\Programs\\Fiji.app')
print(f"ImageJ version: {ij.getVersion()}")
```

The error I'm getting is this:

```
Failed to bootstrap the artifact.
Possible solutions:
* Double check the endpoint for correctness (https://search.maven.org/).
* Add needed repositories to ~/.jgorc [repositories] block (see README).
* Try with an explicit version number (release metadata might be wrong).

Full Maven error output:
        [ERROR] [ERROR] Some problems were encountered while processing the POMs:
        [ERROR] Non-resolvable import POM: Could not transfer artifact io.scif:scifio-labeling:pom:0.3.1 from/to scijava.public (https://maven.scijava.org/content/groups/public): transfer failed for https://maven.scijava.org/content/groups/public/io/scif/scifio-labeling/0.3.1/scifio-labeling-0.3.1.pom @ line 8, column 29
        [ERROR] The build could not read 1 project -> [Help 1]
        [ERROR]   
        [ERROR]   The project io.scif-BOOTSTRAPPER:scifio-labeling-BOOTSTRAPPER:0 (C:\Users\luisa.oliveira\.jgo\io.scif\scifio-labeling\0.3.1\eb3228841e43c0aa0cffa924ea6aa524384a3685113d54510c0ed985c20d2ab0\pom.xml) has 1 error
        [ERROR]     Non-resolvable import POM: Could not transfer artifact io.scif:scifio-labeling:pom:0.3.1 from/to scijava.public (https://maven.scijava.org/content/groups/public): transfer failed for https://maven.scijava.org/content/groups/public/io/scif/scifio-labeling/0.3.1/scifio-labeling-0.3.1.pom @ line 8, column 29: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 2]
        [ERROR] 
        [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
        [ERROR] Re-run Maven using the -X switch to enable full debug logging.
        [ERROR] 
        [ERROR] For more information about the errors and possible solutions, please read the following articles:
        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
        [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Traceback (most recent call last):
  File "c:\Users\--\Programs\VScode\ImageJ Plugin\PluginTeste.py", line 3, in <module>
    ij = imagej.init('C:\\Users\\l--\\Programs\\Fiji.app')
  File "C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\imagej\__init__.py", line 1498, in init
    raise RuntimeError("Failed to create a JVM with the requested environment.")
RuntimeError: Failed to create a JVM with the requested environment.
```

I used the ImageJ doctor and got this response:

```
Checking Python:
--> Python executable = C:\Users\--\AppData\Local\Programs\Python\Python310\python.exe

Checking environment:
--> It looks like you are NOT running inside a Conda environment.

Checking Python dependencies:
--> jgo: C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\jgo\__init__.py
--> scyjava: C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\scyjava\__init__.py
--> imglyb: C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\imglyb\__init__.py
--> pyimagej: C:\Users\--\AppData\Local\Programs\Python\Python310\lib\site-packages\imagej\__init__.py

Checking Maven:
--> Maven executable = C:\Users\--\Programs\apache-maven-3.8.6\bin\mvn.CMD
$ mvn -v
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: C:\Users\--\Programs\apache-maven-3.8.6
Java version: 18.0.2.1, vendor: Oracle Corporation, runtime: C:\Program Files (x86)\Java\jdk-18.0.2.1
Default locale: pt_BR, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Checking Java:
--> JAVA_HOME = C:\Program Files (x86)\Java\jdk-18.0.2.1
--> Java executable = C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.EXE
$ java -version
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) Client VM (build 25.341-b10, mixed mode)

Questions and advice for you:
--> Did you intend to activate a Conda environment?
 
```

Could someone please help? I'm really struggling on this for days  :(

**Comment by ctrueden** [comment]
@lsdanttas I think the important part of your error message is this:

> PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

From the ImageJ doctor, it looks like you are using Java 18. But PyImageJ is not supported with that version of Java. Try with Java 8 or Java 11 please.

I recommend using [mambaforge](https://github.com/conda-forge/miniforge#mambaforge) to create an encapsulated environment that includes Java and all needed Python packages. But if you would rather not, and instead want to keep doing it how you are doing it, then you can set the `JAVA_HOME` environment variable to point to a Java 11 or Java 8 installation.

**Comment by lsdanttas** [comment]
@ctrueden I will try that, thak you!
