### ISSUE TITLE
Google Colab example in Install.md yields VerifyError

### ISSUE THREAD

**Issue by gselzer** [imagej/pyimagej#248]
Running the [Google Colab](https://github.com/imagej/pyimagej/blob/main/doc/Install.md#dynamic-installation-within-google-colab), example, I get the following exception running this line:
```python
ij.py.run_plugin("Filter Rank", {"window": 3, "randomise": True}, imp=imp)
```
```
[java.lang.Enum.toString] java.lang.VerifyError: (class: Filter_Rank, method: setup signature: (Ljava/lang/String;Lij/ImagePlus;)I) Incompatible object argument for function call
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at ij.IJ.runUserPlugIn(IJ.java:235)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:319)
	at ij.IJ.run(IJ.java:409)
[java.lang.Enum.toString] 
```

Can anyone else replicate this?

**Comment by CanYing0913** [comment]
I tried with code in `install.md` and replicated the same error. I then tried with my customized plugin and it worked fine (You can try my (notebook)[https://colab.research.google.com/drive/1FYMh60YdnXAjRTJ9a07Vp8-hnscjAWnj?usp=sharing]).

With my local Fiji installation, I could not find a plugin called Filter Rank (Contrast Enhancer neither). I suspect it is not the standard way to call this plugin:
> `ij.py.run_plugin("Filter Rank", {"window": 3, "randomise": True}, imp=imp)`.

Adding on top of this, I found a `contrast enhancer` using Fiji "find command" utility.

**Comment by hinerm** [comment]
Oh and FWIW I get a different error 🙄 

```
[/usr/local/lib/python3.11/dist-packages/imagej/__init__.py](https://localhost:8080/#) in run_plugin(self, plugin, args, ij1_style, imp)
    320             self._ij.IJ.run(plugin, argline)
    321         else:
--> 322             self._ij.IJ.run(imp, plugin, argline)
    323 
    324     def run_script(self, language: str, script: str, args=None):

java.lang.RuntimeException: java.lang.RuntimeException: Macro canceled
```

But I'm not sure it matters. It looks like the [version of this plugin changed](https://github.com/imagej/pyimagej/commit/2191b9f928e66af4c96159cd7b5300f47cf9293a) and I don't see any logic in the [current version](https://imagej.net/ij/plugins/download/Filter_Rank.java) to parse args headlessly.

**Comment by hinerm** [comment]
Note that the initialization with a local imagej installation currently does not support loading .class-based plugins, making it impossible to reproduce this for the time being.
