### ISSUE TITLE
java.lang.RuntimeException: Macro canceled with DiameterJ Segment

### ISSUE THREAD

**Issue by marilin99** [imagej/pyimagej#251]
Hi 

I am trying to run the DiameterJ Segment plugin using pyimagej. 
After initialising the object, opening an image and converting the image to imageplus:
```ij = imagej.init()
image = ij.io().open(PATH_1)
imp = ij.py.to_imageplus(image)
```

I run the following command: 

`ij.IJ.run(imp, "DiameterJ Segment", "do=Yes image=1024 image_0=768 top=0 top_0=0 bottom=1024 bottom_0=650 stat. do_0=No choose=/home/marilin/Documents/ESP/diameterJ_test/sem_test")`

I get a Java exception about the Macro being canceled with the following output: 

```
Traceback (most recent call last):
  File "IJ.java", line 409, in ij.IJ.run
  File "IJ.java", line 322, in ij.IJ.run
  File "IJ.java", line 423, in ij.IJ.testAbort
  File "IJ.java", line 2484, in ij.IJ.abort
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marilin/Documents/ESP/master_thesis/scripts/pyimagej_test.py", line 69, in <module>
    ij.IJ.run(imp, "DiameterJ Segment", "do=Yes image=1024 image_0=768 top=0 top_0=0 bottom=1024 bottom_0=650 stat. do_0=No choose=/home/marilin/Documents/ESP/diameterJ_test/sem_test")
java.lang.RuntimeException: java.lang.RuntimeException: Macro canceled
```
Additionally, I have tried to add the custom plugins directory to sj config and use the `run_plugin()` , alas received the same error about the macro being canceled. 
I also tried using the `run_macro()` but ended with a similar result of an unrecognized command "DiameterJ Segment". 

I know the error is pretty verbose, but is there any way to successfully run this plugin in pyimagej?

**Comment by elevans** [comment]
Hi @marilin99. Sorry for the late reply. I've took a look at DiameterJ and I also have issues running it. After searching around it seems that DiameterJ has some incompatibilities with ImageJ/Fiji (see this [post](https://forum.image.sc/t/diameterj-will-not-run-segmentation-or-analysis-plugin/22066/20) for more details). A couple of questions:

- What version of DiameterJ and Fiji are you using with PyImageJ?
- Are you using a single image or a directory of images?
- If you're using a single image, have you tried Nathan's (NHotaling)'s quick fix (i.e. deleting the `var` references in the DiameterJ macro)?

My current guess is that the plugin is failing due to the incompatibilities with ImageJ/Fiji and is throwing a macro cancelled error.

**Comment by ctrueden** [comment]
@marilin99 One other question: are you able to use DiameterJ successfully from within the regular Fiji application? I.e. is it only in PyImageJ that it fails? Or does it fail in Fiji, too?

**Comment by marilin99** [comment]
Hey, 
this is just a message to say that I have seen your comments but have not had the time to look into this issue again. thank you for your responses and questions - will get around this again once my thesis is done :))

**Comment by IssaMBarl** [comment]
Hey,
Sorry for any disturbance, btw, I was wondering if there is any notebook showing DiameterJ use with pyimagej ?
It may be helpful to disentangle such issues, and actually, many people asking such questions on several other forum topics.

Thanks for your time :)

**Comment by elevans** [comment]
Hi @IssaMBarl, we do not have a specific section on using DiameterJ with PyImageJ. While I think some people would find that helpful, I'm hesitant to create new documentation for a specific plugin.  DiameterJ hasn't been maintained for ~9 years (see the [repository](https://github.com/NHotaling/DiameterJ)) making compatibility with current/future versions of PyImageJ unknown. For example this issue that you opened could be from the incompatibility with modern Fiji linked in the post. Creating the specific documentation for DiameterJ would also create an expectation that it _works_ in the future, which we cannot guarantee. A better place to put this kind of content might be on the [ImageJ wiki](https://imagej.net/). Here's an example of [ImgLib2](https://imagej.net/libs/imglib2/examples) examples with snippets of code on the wiki.

But thats only if DiameterJ works with Fiji. Have you gotten DiameterJ to work for you with regular Fiji? Did try deleting the `var` references as suggested by the imagesc forum post?
