### ISSUE TITLE
SystemError: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by chautuankien** [imagej/pyimagej#272]
I am having some issues related to pyimagej initialization. I followed the installization instruction by installing pyimagej vis mamba/conda. I was able to create the virtual envs, but when I execute my code, it got error in this line. How can i fix this

`ij = imagej.init("2.5.0", mode='interactive')`

The error is: 

Traceback (most recent call last):
  File "app.py", line 30, in <module>
    xml_test()
  File "app.py", line 20, in xml_test
    from module.data.porter.type import xml_scratch
  File "C:\Users\KienCT6.Onsiter\OneDrive - FPT Software\Projects\Material Research Project\project_codes\material-analysis-project-v0.1\module\data\porter\type\xml_scratch.py", line 350, in <module>
    ij = imagej.init()
  File "C:\Users\KienCT6.Onsiter\mambaforge\envs\pyimagej_pore\lib\site-packages\imagej\__init__.py", line 1200, in init
    success = _create_jvm(ij_dir_or_version_or_endpoint, mode, add_legacy)
  File "C:\Users\KienCT6.Onsiter\mambaforge\envs\pyimagej_pore\lib\site-packages\imagej\__init__.py", line 1424, in _create_jvm
    sj.start_jvm()
  File "C:\Users\KienCT6.Onsiter\mambaforge\envs\pyimagej_pore\lib\site-packages\scyjava\_java.py", line 234, in start_jvm
    jpype.startJVM(*options, interrupt=True)
  File "C:\Users\KienCT6.Onsiter\mambaforge\envs\pyimagej_pore\lib\site-packages\jpype\_core.py", line 224, in startJVM
    _jpype.startup(jvmpath, tuple(args),
SystemError: java.lang.NoClassDefFoundError: Could not initialize class java.util.zip.Inflater

**Comment by ctrueden** [comment]
@chautuankien What was the solution?
