### ISSUE TITLE
Issue converting ImagePlus into numpy image.

### ISSUE THREAD

**Issue by jayunruh** [imagej/pyimagej#57]
I'm running pyimagej with my local copy of Fiji with pyimagej version 0.5.0 and ImageJ version 2.0.0-rc-69/1.52p.  I'm in UI mode (not headless).

When I try run WindowManager.getCurrentImage(), I get the java object fine but when I run ij.py.from_java I get: "Attribute Error: 'net.imagej.ops.OpService' object has no attribute 'run'."

**Comment by ctrueden** [comment]
Thanks for the report, @jayunruh. This issue will become moot once #46 is resolved. Work is in progress to do that.

**Comment by imagejan** [comment]
@jayunruh for now, you should be able to work around the issue by pinning to `pyjnius` version 1.2.0, see https://github.com/kivy/pyjnius/issues/465.

**Comment by FengZhiheng** [comment]
> I'm running pyimagej with my local copy of Fiji with pyimagej version 0.5.0 and ImageJ version 2.0.0-rc-69/1.52p. I'm in UI mode (not headless).
> 
> When I try run WindowManager.getCurrentImage(), I get the java object fine but when I run ij.py.from_java I get: "Attribute Error: 'net.imagej.ops.OpService' object has no attribute 'run'."


I meet some trouble as following:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PythonProject/NakedSomaToolPython/test/ImageJ_test.py", line 14, in <module>
    ij.py.show(xarray_lenna, cmap='gray')
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 280, in show
    pyplot.imshow(self.from_java(image), interpolation='nearest', cmap=cmap)
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\matplotlib\pyplot.py", line 2651, in imshow
    None else {}), **kwargs)
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\matplotlib\__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\matplotlib\axes\_axes.py", line 5626, in imshow
    im.set_data(X)
  File "C:\Users\FengZhiheng\anaconda3\envs\pyimagej\lib\site-packages\matplotlib\image.py", line 699, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (3, 1279, 853) for image data

Process finished with exit code 1

```

**Comment by elevans** [comment]
The original issue was resolved when we switched from `pyjnius` to `jpype` as well as a switch away from ops image copying. 

@FengZhiheng Regarding your issue we are currently working on improving dimension order translation between Python and Java (ImageJ) see #151.
