### ISSUE TITLE
ij.py.run_macro() failing with java.lang.NullPointerException

### ISSUE THREAD

**Issue by HazenBabcock** [imagej/pyimagej#60]
When I try to run a script version of the `run_macro` example from the `Jupyter` notebook it is failing.

The script:
```
import imagej
ij = imagej.init()
print(ij.getVersion())

macro = """
#@ String name
#@ int age
#@ String city
#@output Object greeting
greeting = "Hello " + name + ". You are " + age + " years old, and live in " + city + "."
"""
args = {
    'name': 'Chuckles',
    'age': 13,
    'city': 'Nowhere'
}
result = ij.py.run_macro(macro, args)
print(result.getOutput('greeting'))
```

The error message:
```
(pyimagej_conda) hb ~/Code/temp$ python ij_macro.py 
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2.0.0-rc-71
[ERROR] Module threw exception
java.lang.NullPointerException
	at org.scijava.script.ScriptModule.getEngine(ScriptModule.java:108)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:129)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Traceback (most recent call last):
  File "ij_macro.py", line 17, in <module>
    result = ij.py.run_macro(macro, args)
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/imagej/imagej.py", line 201, in run_macro
    raise exc
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/imagej/imagej.py", line 198, in run_macro
    return self._ij.script().run("macro.ijm", macro, True, to_java(args)).get()
  File "jnius/jnius_export_class.pxi", line 1044, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 843, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: java.lang.NullPointerException
```

This is with `pyimagej` 0.5.0, `pyjnius` 1.2.0 and `conda` 4.7.12 on Ubuntu 18.04.

`conda create -n pyimagej_conda pyimagej pyjnius=1.2.0 openjdk=8 scikit-image requests`

**Comment by mpinkert** [comment]
Sorry for the late reply.  This is because the default endpoint of `imagej.init()` does not include ImageJ1, and so cannot run ImageJ1 macros.

Try replacing `imagej.init()` with 
```python
ij = imagej.init('net.imagej:imagej+net.imagej:imagej-legacy')
```
to obtain the latest version using both imagej1 and imagej2.

**Comment by HazenBabcock** [comment]
That worked, thanks!

I did have to pin `imglyb` to `0.3.5` to get this to work. With `0.4.0` I got:
```
  File "run_macro.py", line 3, in <module>
    ij = imagej.init('net.imagej:imagej+net.imagej:imagej-legacy')
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/imagej/imagej.py", line 126, in init
    import imglyb
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/imglyb/__init__.py", line 41, in <module>
    from .ndarray_like_as_img import \
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/imglyb/ndarray_like_as_img.py", line 5, in <module>
    from . import accesses
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/imglyb/accesses.py", line 5, in <module>
    Accesses            = autoclass('net.imglib2.img.basictypeaccess.Accesses')
  File "/home/hbabcock/miniconda3/envs/pyimagej_conda/lib/python3.7/site-packages/jnius/reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/img/basictypeaccess/Accesses'
```

**Comment by mpinkert** [comment]
Thanks for the heads up.  You're right, we are correctly incompatible with version 0.4.0 of imglyb.  This is not currently reflected in our installation requirements; we will work to get a quick fix out.

**Comment by ctrueden** [comment]
Should be all clear now with pyimagej 1.0.0!
