### ISSUE TITLE
Cannot initialize pyimagej on Linux

### ISSUE THREAD

**Issue by CsatiZoltan** [imagej/pyimagej#61]
After `import imagej`, the `ij = imagej.init()` command results in the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/imagej/imagej.py", line 126, in init
    import imglyb
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/imglyb/__init__.py", line 38, in <module>
    config = _init_jvm_options()
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/imglyb/__init__.py", line 33, in _init_jvm_options
    import scyjava
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/scyjava/__init__.py", line 140, in <module>
    jnius = _init_jvm()
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/scyjava/__init__.py", line 131, in _init_jvm
    import jnius
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/jnius/__init__.py", line 42, in <module>
    from .reflect import *  # noqa
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/jnius/reflect.py", line 17, in <module>
    class Class(with_metaclass(MetaJavaClass, JavaClass)):
  File "/home/zoltan/anaconda3/envs/imagej/lib/python3.7/site-packages/six.py", line 856, in __new__
    return meta(name, resolved_bases, d)
  File "jnius/jnius_export_class.pxi", line 114, in jnius.MetaJavaClass.__new__
  File "jnius/jnius_export_class.pxi", line 164, in jnius.MetaJavaClass.resolve_class
  File "jnius/jnius_env.pxi", line 11, in jnius.get_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 118, in jnius.get_platform_jnienv
  File "jnius/jnius_jvm_dlopen.pxi", line 87, in jnius.create_jnienv
SystemError: Error calling dlopen(b'/home/zoltan/anaconda3/envs/imagej/lib/server/libjvm.so': b'/home/zoltan/anaconda3/envs/imagej/lib/server/libjvm.so: cannot open shared object file: No such file or directory'
```
`java --version` prints:
```bash
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

The error holds even though I installed _pyimagej_ with `conda create -n pyimagej pyimagej openjdk=8`.

**Comment by CsatiZoltan** [comment]
The problem was that `JAVA_HOME` was not set. I got the idea from [here](https://github.com/kivy/pyjnius/issues/384#issuecomment-451547197).
