### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by gfleetwood** [imagej/pyimagej#65]
I'm using pyimagej on Ubuntu 18.04 running OpenJDK 11 in a conda environment. I had it working before but now its throwing a class error after some upgrades:

* Python 3.6 -> Python 3.7
* conda 4.? -> conda 4.8.2

Now when I run this:

```
import imagej
ij = imagei.init()
```
I get this error:

```
$ python processing-pipeline.py
Traceback (most recent call last):
  File "processing-pipeline.py", line 25, in <module>
    ij = imagej.init()
  File "/home/gordon/miniconda3/envs/vader/lib/python3.7/site-packages/imagej/imagej.py", line 104, in init
    import imglyb
  File "/home/gordon/miniconda3/envs/vader/lib/python3.7/site-packages/imglyb/__init__.py", line 41, in <module>
    from .ndarray_like_as_img import \
  File "/home/gordon/miniconda3/envs/vader/lib/python3.7/site-packages/imglyb/ndarray_like_as_img.py", line 5, in <module>
    from . import accesses
  File "/home/gordon/miniconda3/envs/vader/lib/python3.7/site-packages/imglyb/accesses.py", line 5, in <module>
    Accesses            = autoclass('net.imglib2.img.basictypeaccess.Accesses')
  File "/home/gordon/miniconda3/envs/vader/lib/python3.7/site-packages/jnius/reflect.py", line 159, in autoclass
    c = find_javaclass(clsname)
  File "jnius/jnius_export_func.pxi", line 26, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/img/basictypeaccess/Accesses'
```

I tried `conda update pyimagej` but I got the same error.

**Comment by imagejan** [comment]
You'll have to pin the `imglyb` version to `0.3.5` in your local environment, as the latest version `0.4.0` introduces some breaking changes.

See commit https://github.com/imagej/pyimagej/pull/64/commits/4119442907b5f3c6df503bb57806fd0d3c29e2bd and PR https://github.com/imagej/pyimagej/pull/64.

**Comment by gfleetwood** [comment]
That worked. Thanks!
