### ISSUE TITLE
Running a python script

### ISSUE THREAD

**Issue by Chokerino** [imagej/pyimagej#66]
Hi i installed pyimagej using conda and tried this basic script. I am able to import the package but the 2nd command i.e imagej.init() gets stuck and later i get the following error.
`import imagej
ij = imagej.init('sc.fiji:fiji:2.0.0-pre-10')
ij.getVersion()
from skimage import io
import numpy as np
img = io.imread('https://samples.fiji.sc/new-lenna.jpg')
img = np.mean(img[500:1000,300:850], axis=2)
ij.py.show(img, cmap = 'gray')`

`log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Mar 04, 2020 1:01:01 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
01:01:01.483 [SciJava-377008df-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.SlideBook6Reader
java.lang.ClassNotFoundException: loci.formats.in.SlideBook6Reader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at loci.formats.ClassList.parseLine(ClassList.java:196)
        at loci.formats.ClassList.parseFile(ClassList.java:258)
        at loci.formats.ClassList.<init>(ClassList.java:138)
        at loci.formats.ClassList.<init>(ClassList.java:122)
        at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:79)
        at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:489)
        at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:138)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
        at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
        at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
        at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:458)
        at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
01:01:01.492 [SciJava-377008df-Thread-0] DEBUG loci.formats.ClassList - Could not find loci.formats.in.ScreenReader
java.lang.ClassNotFoundException: loci.formats.in.ScreenReader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at loci.formats.ClassList.parseLine(ClassList.java:196)
        at loci.formats.ClassList.parseFile(ClassList.java:258)
        at loci.formats.ClassList.<init>(ClassList.java:138)
        at loci.formats.ClassList.<init>(ClassList.java:122)
        at loci.formats.ImageReader.getDefaultReaderClasses(ImageReader.java:79)
        at io.scif.bf.BioFormatsFormat.cacheReaderClasses(BioFormatsFormat.java:489)
        at io.scif.bf.BioFormatsFormat.<init>(BioFormatsFormat.java:138)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.scijava.plugin.PluginInfo.createInstance(PluginInfo.java:306)
        at org.scijava.plugin.DefaultPluginService.createInstance(DefaultPluginService.java:237)
        at org.scijava.plugin.DefaultPluginService.createInstances(DefaultPluginService.java:226)
        at org.scijava.plugin.DefaultPluginService.createInstancesOfType(DefaultPluginService.java:217)
        at io.scif.services.DefaultFormatService.lambda$initialize$0(DefaultFormatService.java:458)
        at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by ctrueden** [comment]
@Chokerino Those exceptions are from Bio-Formats, but are non-fatal.

The `imagej.init()` will take a few seconds (at least) the first time you run, because it's downloading and caching Java libraries in the background. Should be quicker on subsequent executions.

Since you closed the issue, I assume all is well for you?

**Comment by Chokerino** [comment]
Yes, sorry it was a mistake on my part.

Coordinator | BioBytes
Btech Undergrad '22 IIITD
