### ISSUE TITLE
imagej.init() crashing with jnius.JavaException: Class not found b'net/imglib2/img/basictypeaccess/Accesses'

### ISSUE THREAD

**Issue by dougngenturi** [imagej/pyimagej#69]
Have run into this on both windows and debian. Not sure what the cause is and have not seen this being reported anywhere. I must be doing something wrong, but I have no clue what.

All the way from a a conda base.

Conda 4.7.12

Steps:
```
conda create -n pyimagej pyimagej openjdk=8
conda activate pyimagej
python -c 'import imagej; ij=imagej.init()'
```

Full trace from a clean system:

```
(base) PS C:\Users\user> conda create -n pyimagej pyimagej openjdk=8
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pyimagej

  added / updated specs:
    - openjdk=8
    - pyimagej


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.11.28 |       hecc5488_0         182 KB  conda-forge
    certifi-2019.11.28         |   py37hc8dfbb8_1         149 KB  conda-forge
    cycler-0.10.0              |             py_2           9 KB  conda-forge
    freetype-2.10.0            |       h563cfd7_1         476 KB  conda-forge
    icu-64.2                   |       he025d50_1        14.1 MB  conda-forge
    imglyb-0.4.0               |   py37h5ca1d4c_0          23 KB  conda-forge
    intel-openmp-2020.0        |              166         1.5 MB
    jgo-0.5.0                  |   py37hc8dfbb8_1          79 KB  conda-forge
    jpeg-9c                    |    hfa6e2cd_1001         314 KB  conda-forge
    kiwisolver-1.1.0           |   py37heaa310e_1          61 KB  conda-forge
    libblas-3.8.0              |           15_mkl         3.5 MB  conda-forge
    libcblas-3.8.0             |           15_mkl         3.5 MB  conda-forge
    libclang-9.0.1             |default_hf44288c_0        20.8 MB  conda-forge
    liblapack-3.8.0            |           15_mkl         3.5 MB  conda-forge
    libpng-1.6.37              |       h7602738_0         1.3 MB  conda-forge
    matplotlib-3.2.0           |                1           6 KB  conda-forge
    matplotlib-base-3.2.0      |   py37h2981e6d_1         7.1 MB  conda-forge
    maven-3.6.0                |                0         8.6 MB  conda-forge
    mkl-2020.0                 |              166        98.9 MB
    numpy-1.18.1               |   py37hc71023c_0         4.7 MB  conda-forge
    openjdk-8.0.192            |             1004        62.4 MB  conda-forge
    openssl-1.1.1d             |       hfa6e2cd_0         4.7 MB  conda-forge
    pip-20.0.2                 |             py_2         1.0 MB  conda-forge
    psutil-5.7.0               |   py37h8055547_1         346 KB  conda-forge
    pyimagej-0.5.0             |           py37_0          68 KB  conda-forge
    pyjnius-1.2.1              |   py37hf78f419_0         192 KB  conda-forge
    pyparsing-2.4.6            |             py_0          59 KB  conda-forge
    pyqt-5.12.3                |   py37h6538335_1         4.7 MB  conda-forge
    python-3.7.6               |h5b45d93_4_cpython        17.8 MB  conda-forge
    python-dateutil-2.8.1      |             py_0         220 KB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    qt-5.12.5                  |       h7ef1ec2_0       104.4 MB  conda-forge
    scyjava-0.4.0              |           py37_0          19 KB  conda-forge
    setuptools-46.0.0          |   py37hc8dfbb8_2         674 KB  conda-forge
    six-1.14.0                 |             py_1          13 KB  conda-forge
    sqlite-3.30.1              |       hfa6e2cd_0         1.1 MB  conda-forge
    tornado-6.0.4              |   py37hfa6e2cd_0         643 KB  conda-forge
    vs2015_runtime-14.16.27012 |       hf0eaf9b_1         1.1 MB
    wheel-0.34.2               |             py_1          24 KB  conda-forge
    wincertstore-0.2           |        py37_1003          13 KB  conda-forge
    zlib-1.2.11                |    h2fa13f4_1006         236 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       368.7 MB

The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/win-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/win-64::certifi-2019.11.28-py37hc8dfbb8_1
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  freetype           conda-forge/win-64::freetype-2.10.0-h563cfd7_1
  icu                conda-forge/win-64::icu-64.2-he025d50_1
  imglyb             conda-forge/win-64::imglyb-0.4.0-py37h5ca1d4c_0
  intel-openmp       pkgs/main/win-64::intel-openmp-2020.0-166
  jgo                conda-forge/win-64::jgo-0.5.0-py37hc8dfbb8_1
  jpeg               conda-forge/win-64::jpeg-9c-hfa6e2cd_1001
  kiwisolver         conda-forge/win-64::kiwisolver-1.1.0-py37heaa310e_1
  libblas            conda-forge/win-64::libblas-3.8.0-15_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-15_mkl
  libclang           conda-forge/win-64::libclang-9.0.1-default_hf44288c_0
  liblapack          conda-forge/win-64::liblapack-3.8.0-15_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h7602738_0
  matplotlib         conda-forge/win-64::matplotlib-3.2.0-1
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.2.0-py37h2981e6d_1
  maven              conda-forge/win-64::maven-3.6.0-0
  mkl                pkgs/main/win-64::mkl-2020.0-166
  numpy              conda-forge/win-64::numpy-1.18.1-py37hc71023c_0
  openjdk            conda-forge/win-64::openjdk-8.0.192-1004
  openssl            conda-forge/win-64::openssl-1.1.1d-hfa6e2cd_0
  pip                conda-forge/noarch::pip-20.0.2-py_2
  psutil             conda-forge/win-64::psutil-5.7.0-py37h8055547_1
  pyimagej           conda-forge/win-64::pyimagej-0.5.0-py37_0
  pyjnius            conda-forge/win-64::pyjnius-1.2.1-py37hf78f419_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pyqt               conda-forge/win-64::pyqt-5.12.3-py37h6538335_1
  python             conda-forge/win-64::python-3.7.6-h5b45d93_4_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m
  qt                 conda-forge/win-64::qt-5.12.5-h7ef1ec2_0
  scyjava            conda-forge/win-64::scyjava-0.4.0-py37_0
  setuptools         conda-forge/win-64::setuptools-46.0.0-py37hc8dfbb8_2
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/win-64::sqlite-3.30.1-hfa6e2cd_0
  tornado            conda-forge/win-64::tornado-6.0.4-py37hfa6e2cd_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_1
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  wincertstore       conda-forge/win-64::wincertstore-0.2-py37_1003
  zlib               conda-forge/win-64::zlib-1.2.11-h2fa13f4_1006


Proceed ([y]/n)? y


Downloading and Extracting Packages
pyparsing-2.4.6      | 59 KB     | ############################################################################ | 100%
numpy-1.18.1         | 4.7 MB    | ############################################################################ | 100%
libcblas-3.8.0       | 3.5 MB    | ############################################################################ | 100%
scyjava-0.4.0        | 19 KB     | ############################################################################ | 100%
tornado-6.0.4        | 643 KB    | ############################################################################ | 100%
wincertstore-0.2     | 13 KB     | ############################################################################ | 100%
matplotlib-3.2.0     | 6 KB      | ############################################################################ | 100%
psutil-5.7.0         | 346 KB    | ############################################################################ | 100%
libblas-3.8.0        | 3.5 MB    | ############################################################################ | 100%
libclang-9.0.1       | 20.8 MB   | ############################################################################ | 100%
kiwisolver-1.1.0     | 61 KB     | ############################################################################ | 100%
vs2015_runtime-14.16 | 1.1 MB    | ############################################################################ | 100%
jpeg-9c              | 314 KB    | ############################################################################ | 100%
icu-64.2             | 14.1 MB   | ############################################################################ | 100%
python_abi-3.7       | 4 KB      | ############################################################################ | 100%
pyjnius-1.2.1        | 192 KB    | ############################################################################ | 100%
qt-5.12.5            | 104.4 MB  | ############################################################################ | 100%
imglyb-0.4.0         | 23 KB     | ############################################################################ | 100%
mkl-2020.0           | 98.9 MB   | ############################################################################ | 100%
setuptools-46.0.0    | 674 KB    | ############################################################################ | 100%
sqlite-3.30.1        | 1.1 MB    | ############################################################################ | 100%
pyqt-5.12.3          | 4.7 MB    | ############################################################################ | 100%
python-3.7.6         | 17.8 MB   | ############################################################################ | 100%
maven-3.6.0          | 8.6 MB    | ############################################################################ | 100%
intel-openmp-2020.0  | 1.5 MB    | ############################################################################ | 100%
matplotlib-base-3.2. | 7.1 MB    | ############################################################################ | 100%
certifi-2019.11.28   | 149 KB    | ############################################################################ | 100%
pyimagej-0.5.0       | 68 KB     | ############################################################################ | 100%
ca-certificates-2019 | 182 KB    | ############################################################################ | 100%
libpng-1.6.37        | 1.3 MB    | ############################################################################ | 100%
openjdk-8.0.192      | 62.4 MB   | ############################################################################ | 100%
six-1.14.0           | 13 KB     | ############################################################################ | 100%
jgo-0.5.0            | 79 KB     | ############################################################################ | 100%
wheel-0.34.2         | 24 KB     | ############################################################################ | 100%
python-dateutil-2.8. | 220 KB    | ############################################################################ | 100%
liblapack-3.8.0      | 3.5 MB    | ############################################################################ | 100%
freetype-2.10.0      | 476 KB    | ############################################################################ | 100%
cycler-0.10.0        | 9 KB      | ############################################################################ | 100%
pip-20.0.2           | 1.0 MB    | ############################################################################ | 100%
openssl-1.1.1d       | 4.7 MB    | ############################################################################ | 100%
zlib-1.2.11          | 236 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pyimagej
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) PS C:\Users\user> conda activate pyimagej
(pyimagej) PS C:\Users\user> python
Python 3.7.6 | packaged by conda-forge | (default, Mar  5 2020, 14:47:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imagej
>>> ij = imagej.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pyimagej\lib\site-packages\imagej\imagej.py", line 126, in init
    import imglyb
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pyimagej\lib\site-packages\imglyb\__init__.py", line 41, in <module>
    from .ndarray_like_as_img import \
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pyimagej\lib\site-packages\imglyb\ndarray_like_as_img.py", line 5, in <module>
    from . import accesses
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pyimagej\lib\site-packages\imglyb\accesses.py", line 5, in <module>
    Accesses            = autoclass('net.imglib2.img.basictypeaccess.Accesses')
  File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\pyimagej\lib\site-packages\jnius\reflect.py", line 208, in autoclass
    c = find_javaclass(clsname)
  File "jnius\jnius_export_func.pxi", line 28, in jnius.find_javaclass
jnius.JavaException: Class not found b'net/imglib2/img/basictypeaccess/Accesses'
>>>
```

**Comment by imagejan** [comment]
Try pinning `imglyb` to version `0.3.5` in your local environment. This should be fixed with the next release of `pyimagej`.

See #65 and #64.
